version: "3"

services:
    remote_chrome:
        image: selenium/standalone-chrome
        networks:
            - odoodocker_default
    zap:
        image: owasp/zap2docker-stable
        ports:
            - 8888:8080
            - 8099:8090
        command:  zap-webswing.sh
        networks:
            - odoodocker_default
        volumes:
            - ./data/:/zap-data/
    testscripts:
        image: node:14
        volumes:
            - ./testing:/usr/local/app
        environment:
            - SELENIUM_BROWSER=chrome
            - SELENIUM_REMOTE_URL=http://remote_chrome:4444/wd/hub
            - SITE_URL=http://odoo:8069
            - START_XVFB=false
        command: >
            sh -c "cd /usr/local/app
            && npm install
            && npm run test"
        networks:
            - odoodocker_default
networks:
    odoodocker_default:
        external: true