version: "3"

services:
    odoo:
        build: .
        depends_on:
            - db
        ports:
            - 8069:8069
        environment:
            - HOST=db
            - USER=odoo
            - PASSWORD=odoo
            - NAME=odoo
            - ODOO_DBNAME=${ODOO_DBNAME:-local-dev}
        volumes:
            - ./add-ons:/mnt/extra-addons
            - ./odoo-dev.conf:/etc/odoo/odoo.conf
            - ./scripts:/scripts

    db:
        image: postgres:11
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        volumes:
            - odoo-db-data:/var/lib/postgresql/

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        ports:
            - 8070:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@example.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - ./servers.json:/pgadmin4/servers.json

volumes:
    odoo-db-data:
