version: "3"

services: 
    odoo:
        image: odoo:13.0
        depends_on: 
            - db
        ports: 
            - 8069:8069
        environment: 
            - HOST=db
            - USER=odoo
            - PASSWORD=odoo
            - NAME=odoo
        volumes:
            - ./add-ons:/var/lib/odoo/addons/13.0
            - ./odoo.conf:/etc/odoo/odoo.conf

    db:
        image: postgres:11
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        volumes:
            - odoo-db-data:/var/lib/postgresql/

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        ports:
            - 8070:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@example.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - ./servers.json:/pgadmin4/servers.json

volumes: 
    odoo-db-data:
